server:
    port: 9000

management:
    address: 127.0.0.1
    port: 9100

logging:
    level:
        com.linecorp.sample: DEBUG
# 追加
linecorp:
    platform:
        channel:
            channelId: ${LINECORP_PLATFORM_CHANNEL_CHANNELID}
            channelSecret: ${LINECORP_PLATFORM_CHANNEL_CHANNELSECRET} 
            callbackUrl: ${LINECORP_PLATFORM_CHANNEL_CALLBACKURL}
